#!/bin/bash

# Perform Django database migrations
python manage.py migrate --no-input

# Collect static files
python manage.py collectstatic --no-input

# Run Python application server
exec gunicorn --bind=0.0.0.0:8080 --workers=2 --access-logfile=- --error-logfile=- ZTF_TOM.wsgi:application
